name: Android Release

on:
  push:
    tags:
      - 'f*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup ndk
      run: |
        yes 2>/dev/null | sudo $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;16.1.4479499" "cmake;3.10.2.4988404"

    - name: Init extra for android
      run: |
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/
        bash init-android.sh
        bash init/init-android-boringssl.sh
        bash init/init-android-libsrt.sh

    - name: Build ssl and ffmpeg
      run: |
        cd android/contrib
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/
        bash compile-boringssl.sh all
        wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl
        chmod +x gas-preprocessor.pl && sudo mv gas-preprocessor.pl /usr/local/bin/
        bash compile-ffmpeg.sh all

    - name: Gradle build and publish
      working-directory: android/ijkplayer
      env:
        NEXUS_USERNAME: befovy
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGN_KEYID }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGN_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGN_PASSWORD }}
      run: |
        export ANDROID_NDK=$ANDROID_HOME/ndk/16.1.4479499/
        ./gradlew build
        ./gradlew -PNEXUS_PASSWORD=${NEXUS_PASSWORD} :fijkplayer-full:uploadArchives
        zip -r Symbols.zip fijkplayer-full/build/intermediates/cmake/release/obj

    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace('refs/tags/', '');

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ steps.tag.outputs.result }}
        draft: false
        artifacts: "./android/ijkplayer/Symbols.zip"
        allowUpdates: true
