name: iOS Release

on:
  push:
    tags:
      - 'f*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init extra for iOS
      run: |
        bash init-ios-openssl.sh
        bash init-ios.sh

    - name: Build ssl and ffmpeg
      working-directory: ios
      run: |
        bash compile-openssl.sh all
        bash compile-ffmpeg.sh all

    - name: XCode build ijkplayer
      working-directory: ios/IJKMediaPlayer
      run: xcodebuild -project IJKMediaPlayer.xcodeproj -configuration Release -scheme Universal


    - name: Extract tag name
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace('refs/tags/', '');

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        artifacts: "./ios/CocoaPodsPub/IJKMediaPlayer.tar.gz"
        allowUpdates: true
